name: stepfront_api
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.3.0
  hooks_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  flutter_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1
  animate_do: ^2.1.0
  flutter_lints: ^2.0.0
  flash: ^2.0.3+2
  dio: ^4.0.6
  go_router: ^3.1.1
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/

